git clone https://github.com/maglev/maglev 
git clone https://github.com/maglev/nio4r 
git clone https://github.com/maglev/maglev.github.com 
git clone https://github.com/maglev/webtools 
git clone https://github.com/maglev/json 
git clone https://github.com/maglev/nokogiri 
git clone https://github.com/maglev/eventmachine 
git clone https://github.com/maglev/007 
git clone https://github.com/maglev/retwis-rb 
git clone https://github.com/maglev/mspec 
git clone https://github.com/maglev/rvm 
git clone https://github.com/maglev/rubyspec 
git clone https://github.com/maglev/liquid 
git clone https://github.com/maglev/bcrypt-ruby 
git clone https://github.com/maglev/linenoise 
git clone https://github.com/maglev/maglev-topaz-scripts 
git clone https://github.com/maglev/discount 
git clone https://github.com/maglev/rdiscount 
git clone https://github.com/maglev/tesla 
git clone https://github.com/maglev/builder 
git clone https://github.com/maglev/seashell
git clone https://github.com/maglev/gemstone-scripts
