language: ruby
script:
  - bundle exec rspec
jdk:
  - openjdk7
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - rbx-2
  - jruby-head
allow_failures:
  - rvm: jruby-head
notifications:
  recipients:
    - brixen@gmail.com
