git clone https://github.com/rubinius/homebrew-apps.git
git clone https://github.com/rubinius/chruby
git clone https://github.com/rubinius/rubinius
git clone https://github.com/rubinius/heroku-canary-2
git clone https://github.com/rubinius/rubinius-ast
git clone https://github.com/rubinius/atom-rubinius-terminal
git clone https://github.com/rubinius/rubinius.github.io
git clone https://github.com/rubinius/rubinius-melbourne
git clone https://github.com/rubinius/rubinius-debugger
git clone https://github.com/rubinius/rubinius-compiler
git clone https://github.com/rubinius/rubinius-book
git clone https://github.com/rubinius/rubinius-x
git clone https://github.com/rubinius/influxdb-grafana
git clone https://github.com/rubinius/heroku-canary-1
git clone https://github.com/rubinius/daedalus-core
git clone https://github.com/rubinius/rubinius-processor
git clone https://github.com/rubinius/collateral
git clone https://github.com/rubinius/rubinius-toolset
git clone https://github.com/rubinius/rubinius-benchmark
git clone https://github.com/rubinius/rubinius-bridge
git clone https://github.com/rubinius/travis-canary
git clone https://github.com/rubinius/rubinius-languages
git clone https://github.com/rubinius/rapa
git clone https://github.com/rubinius/rubinius-instructions
git clone https://github.com/rubinius/nokogiri
git clone https://github.com/rubinius/bundler-canary
git clone https://github.com/rubinius/rubinius-profiler
git clone https://github.com/rubinius/test-unit-canary
git clone https://github.com/rubinius/rubinius-coverage
git clone https://github.com/rubinius/ffi2-generators
git clone https://github.com/rubinius/ruby-build
git clone https://github.com/rubinius/heroku-rbx-puma-rails-app
git clone https://github.com/rubinius/oniguruma
git clone https://github.com/rubinius/hiredis-rb
git clone https://github.com/rubinius/rubinius-docs
git clone https://github.com/rubinius/rubinius-ir
git clone https://github.com/rubinius/ffi2
git clone https://github.com/rubinius/xapi
git clone https://github.com/rubinius/ruby-hl7
git clone https://github.com/rubinius/rb-fsevent
git clone https://github.com/rubinius/ffi
git clone https://github.com/rubinius/rubinius-actor
git clone https://github.com/rubinius/rubinius-core-api
git clone https://github.com/rubinius/rugged
git clone https://github.com/rubinius/melbourne
git clone https://github.com/rubinius/yajl-ruby
git clone https://github.com/rubinius/simple-rails-bench
git clone https://github.com/rubinius/rbxday
git clone https://github.com/rubinius/rubinius-report
git clone https://github.com/rubinius/rubinius-status
git clone https://github.com/rubinius/ruby-oci8
git clone https://github.com/rubinius/hpricot
git clone https://github.com/rubinius/system-timer
