development:
  adapter: postgresql
  database: redmine_development
  host: localhost
  username: root
  password: 
  encoding: utf8

test:
  adapter: postgresql
  database: redmine_test
  host: localhost
  username: root
  password: 
  encoding: utf8

production:
  adapter: postgresql
  database: redmine
  host: localhost
  username: root
  password: 
  encoding: utf8
